Author: Tanay Yadav

Roll No: AI20BTECH11026

Assignment 2

# Q4

In [249]:
#importing the required libraries

import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.metrics import accuracy_score

In [250]:
# preparing the training and testing datasets

temp_train = pd.read_csv('train_dataset.csv')
temp_test = pd.read_csv('test_dataset.csv')

In [251]:
temp_train.head()

label  feature 1  feature 2
0    6.0   0.341092  -4.528937
1    5.0   0.444131  -5.496812
2    4.0   0.231002  -2.886750
3    7.0   0.200275  -3.534375
4    3.0   0.291936  -4.352062

In [252]:
temp_test.head()

label  feature 1  feature 2
0    9.0   0.272178  -4.847937
1    6.0   0.265133  -5.102000
2    3.0   0.335926  -2.921562
3    6.0   0.264850  -4.156625
4    6.0   0.345338  -6.718438

In [253]:
# selecting the labels 1 and 5 for training and testing

train_data = temp_train[temp_train['label'].isin([1,5])]
test_data = temp_test[temp_test['label'].isin([1,5])]
train_data.head()

label  feature 1  feature 2
1     5.0   0.444131  -5.496812
7     1.0   0.123043  -0.707875
9     1.0   0.113859  -0.931375
12    1.0   0.115371  -0.386000
13    1.0   0.102281  -0.378812

In [254]:
# assigning the labels to the respective arrays

train_label = train_data['label']
test_label = test_data['label']
train_label.head()

1     5.0
7     1.0
9     1.0
12    1.0
13    1.0
Name: label, dtype: float64

In [255]:
# dropping the label columns from the datasets.

train_data = train_data.drop(columns = ['label'])
test_data = test_data.drop(columns = ['label'])
train_data.head()

feature 1  feature 2
1    0.444131  -5.496812
7    0.123043  -0.707875
9    0.113859  -0.931375
12   0.115371  -0.386000
13   0.102281  -0.378812

# Q4 (a)

In [256]:
# initialising the classifier clf as an SVM with a linear kernel

clf = svm.SVC(kernel = 'linear')

In [257]:
# fitting the training dataset

clf.fit(train_data,train_label)

SVC(kernel='linear')

In [258]:
# getting the predictions for the training dataset and calculating the training error

pred_train_label = clf.predict(train_data)
train_accu = accuracy_score(train_label, pred_train_label)
print('Training error =', 1 - train_accu)

Training error = 0.0038436899423446302


In [259]:
# getting the predictions for the testing dataset and calculating the testing error

pred_test_label = clf.predict(test_data)
test_accu = accuracy_score(test_label, pred_test_label)
print('Testing error =',1 - test_accu)

Testing error = 0.021226415094339646


In [260]:
# calculating the number of support vectors for the classifier fitter above

clf.n_support_

array([14, 14])

*Observations:*

From the above results we get that the accuracy over the given test set is $0.9787735849056604$
and the number of support vectors for both the classes i.e. $1(+1)$ and $5(-1)$ are $14$ each.

# Q4(b)

(i) Using the first $50$ data points from the training dataset.

In [261]:
# copying the first 50 training datapoints into a different array

train_50 = train_data.iloc[0:50]
train_label_50 = train_label.iloc[0:50]

In [262]:
clf_50 = svm.SVC(kernel = 'linear', gamma = 0.1) 

In [263]:
clf_50.fit(train_50,train_label_50)

SVC(gamma=0.1, kernel='linear')

In [264]:
pred_test_label_50 = clf_50.predict(test_data)
test_accu_50 = accuracy_score(test_label, pred_test_label_50)
print('Testing error =',1 - test_accu_50)

Testing error = 0.018867924528301883


In [265]:
clf_50.n_support_

array([1, 1])

Testing accuracy while training for first $50$ training datapoints is $0.9811320754716981$ with $1$ support vector each for both the classes.

----------------------------------------------------------------
(ii) Using the first $100$ data points from the training dataset.

In [266]:
# copying the first 100 training datapoints into a different array

train_100 = train_data.iloc[0:100]
train_label_100 = train_label.iloc[0:100]

In [267]:
clf_100 = svm.SVC(kernel = 'linear', gamma = 0.1) 

In [268]:
clf_100.fit(train_100,train_label_100)

SVC(gamma=0.1, kernel='linear')

In [269]:
pred_test_label_100 = clf_100.predict(test_data)
test_accu_100 = accuracy_score(test_label, pred_test_label_100)
print('Testing error =', 1 - test_accu_100)

Testing error = 0.018867924528301883


In [270]:
clf_100.n_support_

array([2, 2])

Testing accuracy while training for first $100$ training datapoints is $0.9811320754716981$ with $2$ support vectors each for both the classes.

----------------------------------------------------------------
(iii) Using the first $200$ data points from the training dataset.

In [271]:
# copying the first 200 training datapoints into a different array

train_200 = train_data.iloc[0:200]
train_label_200 = train_label.iloc[0:200]

In [272]:
clf_200 = svm.SVC(kernel = 'linear', gamma = 0.1) 

In [273]:
clf_200.fit(train_200,train_label_200)

SVC(gamma=0.1, kernel='linear')

In [274]:
pred_test_label_200 = clf_200.predict(test_data)
test_accu_200 = accuracy_score(test_label, pred_test_label_200)
print('Testing error =', 1 - test_accu_200)

Testing error = 0.018867924528301883


In [275]:
clf_200.n_support_

array([4, 4])

Testing accuracy while training for first $200$ training datapoints is $0.9811320754716981$ with $4$ support vectors each for both the classes.

----------------------------------------------------------------
(iv) Using the first $800$ data points from the training dataset.

In [276]:
# copying the first 800 training datapoints into a different array

train_800 = train_data.iloc[0:800]
train_label_800 = train_label.iloc[0:800]

In [277]:
clf_800 = svm.SVC(kernel = 'linear', gamma = 0.1) 

In [278]:
clf_800.fit(train_800,train_label_800)

SVC(gamma=0.1, kernel='linear')

In [279]:
pred_test_label_800 = clf_800.predict(test_data)
test_accu_800 = accuracy_score(test_label, pred_test_label_800)
print('Testing error =',1 - test_accu_800)

Testing error = 0.018867924528301883


In [280]:
clf_800.n_support_

array([7, 7])

Testing accuracy while training for first $800$ training datapoints is $0.9811320754716981$ with $7$ support vectors each for both the classes.

*Observations:*  
#### For $50$ training datapoints:  
Testing error = 0.018867924528301883  
Number of support vectors for both the classes = 1.  

#### For $100$ training datapoints:  
Testing error = 0.018867924528301883  
Number of support vectors for both the classes = 2.  

#### For $200$ training datapoints:  
Testing error = 0.018867924528301883  
Number of support vectors for both the classes = 4.  

#### For $800$ training datapoints:  
Testing error = 0.018867924528301883  
Number of support vectors for both the classes = 7.  



# Q4(c)

## (i)

In [281]:
# creating a classifier SVM with a polynomial kernel having attributes: Q = 2, C = 0.0001

clf_polynomial = svm.SVC(kernel = 'poly', degree = 2, coef0 = 0.0001, gamma = 0.1)
clf_polynomial.fit(train_data, train_label)

print('\n For Q = 2 and C = 0.0001\n')
poly_train = clf_polynomial.predict(train_data)
poly_accu = accuracy_score(train_label, poly_train)
print('\n* Training error =',1 - poly_accu)


poly_test = clf_polynomial.predict(test_data)
poly_accu_test = accuracy_score(test_label, poly_test)
print('\n* Testing error =',1 - poly_accu_test)

print('\n* No. of Support vectors =', clf_polynomial.n_support_)


 For Q = 2 and C = 0.0001


* Training error = 0.004484304932735439

* Testing error = 0.018867924528301883

* No. of Support vectors = [17 17]


In [282]:
# creating a classifier SVM with a polynomial kernel having attributes: Q = 5, C = 0.0001

clf_polynomial = svm.SVC(kernel = 'poly', degree = 5, coef0 = 0.0001, gamma = 0.1)
clf_polynomial.fit(train_data, train_label)

print('\n For Q = 5 and C = 0.0001\n')
poly_train = clf_polynomial.predict(train_data)
poly_accu = accuracy_score(train_label, poly_train)
print('\n* Training error =',1 - poly_accu)


poly_test = clf_polynomial.predict(test_data)
poly_accu_test = accuracy_score(test_label, poly_test)
print('\n* Testing error =',1 - poly_accu_test)

print('\n* No. of Support vectors =', clf_polynomial.n_support_)


 For Q = 5 and C = 0.0001


* Training error = 0.005124919923126248

* Testing error = 0.01650943396226412

* No. of Support vectors = [16 16]


## (ii)

In [283]:
# creating a classifier SVM with a polynomial kernel having attributes: Q = 2, C = 0.001

clf_polynomial = svm.SVC(kernel = 'poly', degree = 2, coef0 = 0.001, gamma = 0.1)
clf_polynomial.fit(train_data, train_label)

print('\n For Q = 2 and C = 0.001\n')
poly_train = clf_polynomial.predict(train_data)
poly_accu = accuracy_score(train_label, poly_train)
print('\n* Training error =',1 - poly_accu)


poly_test = clf_polynomial.predict(test_data)
poly_accu_test = accuracy_score(test_label, poly_test)
print('\n* Testing error =',1 - poly_accu_test)

print('\n* No. of Support vectors =', clf_polynomial.n_support_)


 For Q = 2 and C = 0.001


* Training error = 0.004484304932735439

* Testing error = 0.018867924528301883

* No. of Support vectors = [17 17]


In [284]:
# creating a classifier SVM with a polynomial kernel having attributes: Q = 5, C = 0.001

clf_polynomial = svm.SVC(kernel = 'poly', degree = 5, coef0 = 0.001, gamma = 0.1)
clf_polynomial.fit(train_data, train_label)

print('\n For Q = 5 and C = 0.001\n')
poly_train = clf_polynomial.predict(train_data)
poly_accu = accuracy_score(train_label, poly_train)
print('\n* Training error =',1 - poly_accu)


poly_test = clf_polynomial.predict(test_data)
poly_accu_test = accuracy_score(test_label, poly_test)
print('\n* Testing error =',1 - poly_accu_test)

print('\n* No. of Support vectors =', clf_polynomial.n_support_)


 For Q = 5 and C = 0.001


* Training error = 0.005124919923126248

* Testing error = 0.01650943396226412

* No. of Support vectors = [16 16]


## (iii)

In [285]:
# creating a classifier SVM with a polynomial kernel having attributes: Q = 2, C = 0.01

clf_polynomial = svm.SVC(kernel = 'poly', degree = 2, coef0 = 0.01, gamma = 0.1)
clf_polynomial.fit(train_data, train_label)

print('\n For Q = 2 and C = 0.01\n')
poly_train = clf_polynomial.predict(train_data)
poly_accu = accuracy_score(train_label, poly_train)
print('\n* Training error =',1 - poly_accu)


poly_test = clf_polynomial.predict(test_data)
poly_accu_test = accuracy_score(test_label, poly_test)
print('\n* Testing error =',1 - poly_accu_test)

print('\n* No. of Support vectors =', clf_polynomial.n_support_)


 For Q = 2 and C = 0.01


* Training error = 0.004484304932735439

* Testing error = 0.018867924528301883

* No. of Support vectors = [17 17]


In [286]:
# creating a classifier SVM with a polynomial kernel having attributes: Q = 5, C = 0.01

clf_polynomial = svm.SVC(kernel = 'poly', degree = 5, coef0 = 0.01, gamma = 0.1)
clf_polynomial.fit(train_data, train_label)

print('\n For Q = 5 and C = 0.01\n')
poly_train = clf_polynomial.predict(train_data)
poly_accu = accuracy_score(train_label, poly_train)
print('\n* Training error =',1 - poly_accu)


poly_test = clf_polynomial.predict(test_data)
poly_accu_test = accuracy_score(test_label, poly_test)
print('\n* Testing error =',1 - poly_accu_test)

print('\n* No. of Support vectors =', clf_polynomial.n_support_)


 For Q = 5 and C = 0.01


* Training error = 0.005124919923126248

* Testing error = 0.01650943396226412

* No. of Support vectors = [16 16]


## (iv)

In [287]:
# creating a classifier SVM with a polynomial kernel having attributes: Q = 2, C = 1

clf_polynomial = svm.SVC(kernel = 'poly', degree = 2, coef0 = 1, gamma = 0.1)
clf_polynomial.fit(train_data, train_label)

print('\n For Q = 2 and C = 1\n')
poly_train = clf_polynomial.predict(train_data)
poly_accu = accuracy_score(train_label, poly_train)
print('\n* Training error =',1 - poly_accu)


poly_test = clf_polynomial.predict(test_data)
poly_accu_test = accuracy_score(test_label, poly_test)
print('\n* Testing error =',1 - poly_accu_test)

print('\n* No. of Support vectors =', clf_polynomial.n_support_)


 For Q = 2 and C = 1


* Training error = 0.004484304932735439

* Testing error = 0.021226415094339646

* No. of Support vectors = [15 15]


In [288]:
# creating a classifier SVM with a polynomial kernel having attributes: Q = 5, C = 1

clf_polynomial = svm.SVC(kernel = 'poly', degree = 5, coef0 = 1, gamma = 0.1)
clf_polynomial.fit(train_data, train_label)

print('\n For Q = 5 and C = 1\n')
poly_train = clf_polynomial.predict(train_data)
poly_accu = accuracy_score(train_label, poly_train)
print('\n* Training error =',1 - poly_accu)


poly_test = clf_polynomial.predict(test_data)
poly_accu_test = accuracy_score(test_label, poly_test)
print('\n* Testing error =',1 - poly_accu_test)

print('\n* No. of Support vectors =', clf_polynomial.n_support_)


 For Q = 5 and C = 1


* Training error = 0.004484304932735439

* Testing error = 0.02358490566037741

* No. of Support vectors = [12 14]


i. When $C = 0.0001$, training error is higher at $Q = 5$. -> True  
ii. When $C = 0.001$, the number of support vectors is lower at $Q = 5$. -> True   
iii. When $C = 0.01$, training error is higher at $Q = 5$. -> False   
iv. When $C = 1$, test error is lower at $Q = 5$. -> False

# Q4(d)

In [289]:
# creating an array with all the values of gamma for the rbf kernel

gamma_val = np.array([0.01, 1, 100, 10e4,10e6])

#looping the initialisation of the classifier according to the gamma values in the array
for i in range(0,5):
    clf_rbf = svm.SVC(kernel = 'rbf', gamma = gamma_val[i])
    clf_rbf.fit(train_data, train_label)
    
    print('For C =', gamma_val[i],': ')
    rbf_train = clf_rbf.predict(train_data)
    rbf_accu = accuracy_score(train_label, rbf_train)
    print('Training error =', 1 - (rbf_accu))
    
    rbf_test = clf_rbf.predict(test_data)
    rbf_accu_test = accuracy_score(test_label, rbf_test)
    print('Testing error =', 1 - (rbf_accu_test), '\n')

For C = 0.01 : 
Training error = 0.004484304932735439
Testing error = 0.021226415094339646 

For C = 1.0 : 
Training error = 0.004484304932735439
Testing error = 0.021226415094339646 

For C = 100.0 : 
Training error = 0.0038436899423446302
Testing error = 0.018867924528301883 

For C = 100000.0 : 
Training error = 0.0
Testing error = 0.36556603773584906 

For C = 10000000.0 : 
Training error = 0.0
Testing error = 0.37735849056603776 



*Observations:*  
The lowest training error is for $C = 10^6$.  
The lowest testing error is for $C = 100$.